sudo: false
language: python
python:
  - "2.7"

before_install:
  - export GALAXY_RELEASE=release_16.04

install:
  # html5lib (planemo dep) requires setuptools >= 18.5
  - pip install --upgrade setuptools
  - pip install flake8 planemo
  - planemo conda_init
  - planemo --version
  - echo $TRAVIS_COMMIT_RANGE
  - git diff --name-only $TRAVIS_COMMIT_RANGE | xargs -n1 dirname | ./filter_directories.py | sort -u > changed_repositories.list
  - cat changed_repositories.list

script:
  - cd "$TRAVIS_BUILD_DIR" && flake8 -v --exclude=.git .
  - planemo shed_lint --tools --ensure_metadata --urls --report_level warn --fail_level error --recursive .
  - |
    if [ -s changed_repositories.list ]; then
      while read -r DIR; do planemo conda_install "$DIR"; done < changed_repositories.list
      while read -r DIR; do planemo test --conda_dependency_resolution --galaxy_branch $GALAXY_RELEASE "$DIR" || exit 1; done < changed_repositories.list
    fi
