name: geneseqtofamily
owner: earlhaminst
homepage_url: https://github.com/TGAC/earlham-galaxytools/tree/master/workflows/GeneSeqToFamily
remote_repository_url: https://github.com/TGAC/earlham-galaxytools/tree/master/workflows/GeneSeqToFamily
description: Workflow based on the Ensembl GeneTrees pipeline to identify homologous genes and generate gene trees
long_description: |
  This is a complex workflow, based on the Ensembl GeneTrees pipeline, which uses NCBI BLAST+, hcluster_sg, T-Coffee and TreeBeST to identify homologous genes and generate gene trees.

  The output gene trees can be visualised using the Aequatus.js visualisation plugin.
categories:
- Phylogenetics
type: unrestricted
