name: GeneSeqToFamily
owner: earlhaminst
homepage_url: https://github.com/TGAC/earlham-galaxytools/tree/master/workflows/GeneSeqToFamily
remote_repository_url: https://github.com/TGAC/earlham-galaxytools/tree/master/workflows/GeneSeqToFamily
description: Workflow based on the Ensembl GeneTrees pipeline, to identify homologous genes and generate genetrees.
long_description: |
  This is a non-trivial example workflow using the NCBI BLAST+, hcluster_sg, T-Coffee, TreeBeST, filter FASTA by ID etc for identifying homologous genes.

  This would ideally include a visualisation of the finally gene trees based on Aequatus.
categories:
- Phylogenetics
type: unrestricted
