install_repository_dependencies: true
install_resolver_dependencies: true
install_tool_dependencies: false
tools:
  - name: blast_parser
    owner: earlhaminst
    revisions:
    - '363f3480622d'  # v0.62
    tool_panel_section_label: Phylogenetics
  - name: hcluster_sg
    owner: earlhaminst
    revisions:
    - '1d2de27d7a9c'
    tool_panel_section_label: Phylogenetics
  - name: hcluster_sg_parser
    owner: earlhaminst
    revisions:
    - '02d73e6ca869'
    tool_panel_section_label: Phylogenetics
  - name: t_coffee
    owner: earlhaminst
    revisions:
    - '0a189243186d'
    tool_panel_section_label: Phylogenetics
  - name: treebest_best
    owner: earlhaminst
    revisions:
    - 'b78b529f66db'
    tool_panel_section_label: Phylogenetics
  - name: gafa
    owner: earlhaminst
    revisions:
    - 'b9f1bcf5ee59'
    tool_panel_section_label: Phylogenetics
  - name: gstf_preparation
    owner: earlhaminst
    revisions:
    - 'e8e75a79de59'
    tool_panel_section_label: Phylogenetics
  - name: ete
    owner: earlhaminst
    revisions:
    - '16e925bf567e'
    tool_panel_section_label: Phylogenetics
  - name: ensembl_get_feature_info
    owner: earlhaminst
    revisions:
    - '70e4134eb0ed'
    tool_panel_section_label: Get Data
  - name: ensembl_get_genetree
    owner: earlhaminst
    revisions:
    - '675fd774314e'
    tool_panel_section_label: Get Data
  - name: ensembl_get_sequences
    owner: earlhaminst
    revisions:
    - '0fa1d1cc417d'
    tool_panel_section_label: Get Data
  - name: emboss_5
    owner: devteam
    revisions:
    - 'dba489bfcd62'
    tool_panel_section_label: EMBOSS
  - name: filter_by_fasta_ids
    owner: galaxyp
    revisions:
    - 'dff7df6fcab5'
    tool_panel_section_label: Filter and Sort
  - name: ucsc_fasplit
    owner: iuc
    revisions:
    - '71f649c23021'
    tool_panel_section_label: Text Manipulation
  - name: ncbi_blast_plus
    owner: devteam
    revisions:
    - '2889433c7ae1'
    tool_panel_section_label: BLAST
  - name: text_processing
    owner: bgruening
    revisions:
    - '0a8c6b61f0f4'
    tool_panel_section_label: Text Manipulation
