name: aequatus_datatypes
owner: tgac 
homepage_url: https://github.com/TGAC/tgac-galaxytools/tree/master/tools/aequatus/datatypes/
remote_repository_url: https://github.com/anilthanki/tgac-galaxytools/tree/master/tools/aequatus/datatypes/
description: Datatypes for Aequatus visualisation plugin 
  This is a repository for Aequatus datatype.
categories:
- visualisation
type: unrestricted
